### PR TITLE
Adding the Image Power Spectrum Functions

### PR DESCRIPTION
**Pull request by Zhilei**

### CODE REVIEW

**Comment by HonggeunKim** [comment]
Could you let me do a reviewer?

**Comment by Zhilei** [comment]
Tested being consistent with the results I run in notebooks. Planning to merge over the weekend.
@HonggeunKim Please let me know if you have any suggestions.

**Comment by HonggeunKim** [comment]
I got very similar results with Zhilei's pipeline and Honggeun's pipeline
image

**Comment by Zhilei** [comment]
Thank you for using it! I will merge then.

**Pull request merged**
